networks:
  LPA:
    external: true

volumes:
  minio_storage: {}

services:
  app_backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/build
    links:
      - postgres
    networks:
      - LPA

  app_frontend:
    container_name: frontend
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - LPA

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - LPA

  minio:
    container_name: minio_srv
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
    networks:
      - LPA